version: "3"
services:
  bookstack:
    image: linuxserver/bookstack
    environment:
      DB_HOST: bookstack_db
      DB_USER: bookstack
      DB_PASS: examplepass
      DB_DATABASE: bookstackapp
    volumes:
      - boockstack_data:/config
    networks:
      - bookstack_network
      - proxy
    depends_on:
      - bookstack_db
    restart: unless-stopped

  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: examplepass
    volumes:
      - db:/config
    networks:
      - bookstack_network
    restart: unless-stopped

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/db
  boockstack_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/boockstack_data

networks:
  bookstack_network:
  proxy:
    external: true
