version: '3'

services:

  app:
    image:
    environment:

    volumes:
      -
    ports:
      -
    networks:
      - net
    depends_on:
      -
    restart: unless-stopped


# Volume to speciefic directory example
# volumes:
#   app_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /data/app-data


networks:
  net:
