version: 3
#https://docs.gitea.io/en-us/install-with-docker/
services:
  app:
    image: gitea/gitea
    container_name: gitea
    environment:
      DOMAIN: git.example.local
      #Port to download git by ssh
      SSH_PORT: 222
      DISABLE_SSH: "False"
      DISABLE_REGISTRATION: "True"
      #Requere Sign in to view pages
      REQUIRE_SIGNIN_VIEW: "True"
      DB_TYPE: postgres
      DB_HOST: db:5432
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: gitea
    volumes:
      - ./data:/data
    ports:
      - 3000:3000
      - 222:22
    networks:
      - gitea
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - gitea
    restart: unless-stopped

networks:
  gitea:
