version: '3'

services:
  app:
    image: grafana/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - proxy
    restart: unless-stopped

volumes:
  grafana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/grafana/grafana_data

networks:
  proxy:
    external: true
