version: '3'

services:

  nginx:
    image: jwilder/nginx-proxy:alpine
    # labels:
    #  - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:rw
      - ./nginx/vhost.d:/etc/nginx/vhost.d:rw
      - ./nginx/html:/usr/share/nginx/html:rw
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  letsencrypt:
    # image: jrcs/letsencrypt-nginx-proxy-companion
    # container_name: nextcloud-letsencrypt
    # volumes:
    #  - ./nginx/certs:/etc/nginx/certs:rw
    #  - ./nginx/vhost.d:/etc/nginx/vhost.d:rw
    #  - ./nginx/html:/usr/share/nginx/html:rw
    #  - /etc/localtime:/etc/localtime:ro
    #  - /var/run/docker.sock:/var/run/docker.sock:ro
    # depends_on:
    #  - nginx
    # restart: unless-stopped

  db:
    image: mariadb
    container_name: nextcloud-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud-app
    environment:
      VIRTUAL_HOST: disk.example.com
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: 8aVJAq5X@87&&w
      MYSQL_HOST: db:5432
      NEXTCLOUD_DATA_DIR: /data
      NEXTCLOUD_TRUSTED_DOMAINS: nextcloud disk.example.com
      LETSENCRYPT_HOST: example@example.com
      LETSENCRYPT_EMAIL: example@example.com
    volumes:
      - /data:/data
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
      - ./nextcloud/data:/var/www/html/data
      - ./nextcloud/themes:/var/www/html/themes
    depends_on:
      - db


  onlyoffice:
    image: onlyoffice/documentserver
    container_name: nextcloud-office
    environment:
      VIRTUAL_HOST: docs.example.com
    restart: unless-stopped

volumes:
  db:
