#This project will deploy Nginx with PHP FPM and MadriaDB
version: '3'

services:

  core:
    image: wyveo/nginx-php-fpm
    container_name: nginx-php-core
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
      - ./web_root:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx-php
    restart: unless-stopped

  db:
    image: mariadb
    container_name: nginx-php-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: example-db
      MYSQL_USER: example-user
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - nginx-php
    restart: unless-stopped

networks:
  nginx-php:
