#This project will deploy PHP FPM and MadriaDB
version: '3'

services:

  core:
    image: php:fpm-alpine
    container_name: php-core
    networks:
      - php
      - proxy
    volumes:
      - ./php-fpm.d:/usr/local/etc/php/conf.d
      - /data/nginx/html:/usr/share/nginx/html:ro #Destination path should match nginx web root.
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "20m"

  db:
    image: mariadb
    container_name: php-mariadb
    networks:
      - php
    volumes:
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: example-db
      MYSQL_USER: example-user
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "20m"

networks:
  php:
  proxy:
    external: true
