#This project will deploy PHP FPM ONLY (without web server) and MadriaDB
version: '3'

services:

  core:
    image: php:fpm-alpine
    container_name: php-core
    volumes:
      - ./php-fpm.d:/usr/local/etc/php/conf.d
      - ./webroot:/usr/share/nginx/html:ro #This bind should match your existing webroot
    networks:
      - php
      - proxy
    restart: unless-stopped

  db:
    image: mariadb
    container_name: php-mariadb
    networks:
      - php
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: example-db
      MYSQL_USER: example-user
    restart: unless-stopped

networks:
  php:
  proxy:
    external: true
