version: "3"

# https://github.com/pi-hole/docker-pi-hole/blob/master/README.md

services:
  pihole:
    image: pihole/pihole
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    environment:
      TZ: 'UTC'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - ./conf:/etc/pihole/
      - ./dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
