version: '3'

services:
  poste:
    image: analogic/poste.io
    container_name: poste
    hostname: mail.example.com
    environment:
      TZ: 'UTC'
      HTTPS: 'OFF'
    ports:
      - 25:25
      - 465:465
      - 587:587
      - 993:993
    volumes:
      - poste_data:/data
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  poste_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/poste/poste_data
