version: '3'

services:
  app:
    image: prom/prometheus
    command: --web.enable-lifecycle
    volumes:
      - prometheus_data:/prometheus
    user: root
    networks:
      - proxy
    restart: unless-stopped

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/prometheus/prometheus_data

networks:
  proxy:
    external: true
