version: '3'

services:
  app:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
    user: root
    networks:
      - proxy
    command: --web.enable-lifecycle
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "20m"

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/prometheus/prometheus_data

networks:
  proxy:
    external: true
