version: '3'

services:

  app:
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    volumes:
      - ./config.json:/etc/shadowsocks-rust/config.json
      - ./plugin:/opt/plugin
    networks:
      - caddy_net
    restart: unless-stopped

networks:
  caddy_net:

# Example of config.json
# {
#   "server":"0.0.0.0",
#   "server_port": 8388,
#   "password": "passwd",
#   "timeout": 60,
#   "method": "aes-256-gcm",
#   "fast_open": true,
#   "reuse_port": true,
#   "nameserver": "dns ip",
#   "plugin": "/opt/plugin/xray-plugin_linux_amd64",
#   "plugin_opts": "server;fastOpen"
# }
