version: "3.8"
services:
  app:
    image: matrixdotorg/synapse
    environment:
      SYNAPSE_SERVER_NAME: example.com
      SYNAPSE_REPORT_STATS: "no"
    volumes:
      - synapse_data:/data
    logging:
      driver: "json-file"
      options:
          max-file: 5
          max-size: 20m
    restart: unless-stopped
    networks:
      - proxy
  synapse-admin:
    image: awesometechnologies/synapse-admin
    restart: unless-stopped
    networks:
      - synapse_network
      - proxy
    logging:
      driver: "json-file"
      options:
          max-file: 5
          max-size: 20m

volumes:
  synapse_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/synapse/synapse_data

networks:
  proxy:
    external: true
