version: "3.8"
services:
  app:
    image: matrixdotorg/synapse
    environment:
      SYNAPSE_SERVER_NAME: example.com
      SYNAPSE_REPORT_STATS: "no"
    volumes:
      - synapse_data:/data
    networks:
      - proxy
    restart: unless-stopped

  synapse-admin:
    image: awesometechnologies/synapse-admin
    networks:
      - synapse_network
      - proxy
    restart: unless-stopped


volumes:
  synapse_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/synapse/synapse_data

networks:
  proxy:
    external: true
